bcp staging.airport_out IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\airport_out.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([id])
bcp staging.bikeMgraLogsum IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\bikeMgraLogsum.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK
bcp staging.commtrip IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\report\commtrip.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- speed issues, max packet size, load without primary key and add later
bcp staging.crossBorderTours IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\crossBorderTours.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([id])
bcp staging.crossBorderTrips IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\crossBorderTrips.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([tourID],[tripID])
bcp staging.eetrip IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\report\eetrip.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([ORIG_TAZ],[DEST_TAZ])
bcp staging.eitrip IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\report\eitrip.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK
bcp staging.householdData IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\householdData_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- needs to be parameterized
bcp staging.households IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\input\households.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([hhid])
bcp staging.indivTourData IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\indivTourData_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- needs to be parameterized
bcp staging.indivTripData IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\indivTripData_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- needs to be parameterized
bcp staging.internalExternalTrips IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\internalExternalTrips.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK
bcp staging.jointTourData IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\jointTourData_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- needs to be parameterized
bcp staging.jointTripData IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\jointTripData_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- needs to be parameterized
bcp staging.personData IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\personData_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- needs to be parameterized
bcp staging.persons IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\input\persons.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([perid])
bcp staging.tapskim IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\report\tapskim.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- speed issues, max packet size, load without primary key and add later
bcp staging.tazskim IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\report\tazskim.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -- speed issues, max packet size, load without primary key and add later
bcp staging.visitorTours IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\visitorTours.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([id])
bcp staging.visitorTrips IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\visitorTrips.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([tourID],[tripID])
bcp staging.walkMgraEquivMinutes IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\walkMgraEquivMinutes.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK -h ORDER([i],[j])
bcp staging.walkMgraTapEquivMinutes IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\walkMgraTapEquivMinutes.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK
bcp staging.wsLocResults IN "\\sandag.org\home\shared\TEMP\gks\test_files\new_files\output\wsLocResults_3.csv" -S sql2014a8 -T -d gsc_test -r\n -t, -c -m 0 -e "test.txt" -F 2 -a 16384 -h TABLOCK
